- name: Allow HTTP and HTTPS Traffic
  ansible.builtin.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 80/tcp
    - 443/tcp

- name: Restart Firewall
  ansible.builtin.systemd:
    name: firewalld
    state: restarted
